### ISSUE TITLE
Release for integration

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-aviz#13]
I have tested the simphony-aviz master branch for integration in simphony-framework.

@nathanfranklin , if you could create a tag/release, Aviz/simphony-aviz can be included in the next simphony-framework release.
Thank you.

**Comment by nathanfranklin** [comment]
@kitchoi ,  great.   I will create a release now of what we currently have.  We are planning on making more improvements in the next 5 days. If we do get done earlier, I'll let you know.

**Comment by kitchoi** [comment]
Thanks @nathanfranklin!

**Comment by kitchoi** [comment]
@nathanfranklin, my plan right now is to make two releases for `simphony-framework`, one for `simphony-common 0.2.0` and one for `simphony-common 0.2.2` as some plugins have gone out of sync.

The current master branch of `simphony-aviz` is tested to work with `simphony-common 0.2.0`
However, in order for `simphony-aviz` to be integrated with `simphony-common 0.2.2`, two of the four test cases will need to be handled:

# 

Traceback (most recent call last):
  File "simphony/local/lib/python2.7/site-packages/simphony_aviz/tests/test_snapshot.py", line 10, in <module>
    from simphony.cuds.lattice import make_square_lattice
ImportError: cannot import name make_square_lattice

# 

  File "simphony/local/lib/python2.7/site-packages/simphony_aviz/tests/test_show.py", line 7, in <module>
    from simphony.cuds.lattice import make_square_lattice
ImportError: cannot import name make_square_lattice

**Comment by nathanfranklin** [comment]
@kitchoi ,  Thanks.   I will address that today.

**Comment by nathanfranklin** [comment]
@kitchoi ,  I made a 0.1.0 release.  I addressed the problems with testing that you mentioned and it now supports both simphony-common `0.2.2` and `0.2.0`.

**Comment by nathanfranklin** [comment]
closed by #15
